### ISSUE TITLE
Table not added to schema under circumstances to be determined [edit 2016-06-16]

### ISSUE THREAD

**Issue by RichardGrossman** [SchemaPlus/schema_plus_views#2]
ACTUAL BEHAVIOR
without schema_plus_views gem

create a migration to create table users if you don't have one
or
create any test migration for a different table (not users) if you already have users
rake db:migrate
create users... added to schema (or still there if it was already there)
create a migration for usersx view
rake db:migrate
users table still in schema
usersx view is not added to schema (standard rake behavior)

add schema_plus_views gem to gemfile
bundle
create any test migration for a different table
rake db:migrate
create view usersx... added to schema as expected with gem
create users table... not in schema

EXPECTED BEHAVIOR
create view usersx in schema
create table users in schema

**Comment by ronen** [comment]
@RichardGrossman thanks for the bug report but not sure I'm following it.  Can you paste or gist examples of the migrations that aren't working for you?

**Comment by RichardGrossman** [comment]
If I have a database table named USERS and a view names USERSX, then 

without schema_plus_views: the schema contains USERS but the not the view USERSX, which is how Rails is normally.

WITH schema_plus views: the schema contains the view USERSX but not the table USERS.

The exact steps to reproduce are in the issure report.

**Comment by RichardGrossman** [comment]
I'm guessing the problem is in middleware.rb:

        # Dump views
        def after(env)
          re_view_referent = %r{(?:(?i)FROM|JOIN) \S*\b(\S+)\b}
          env.connection.views.each do |view_name|
            next if env.dumper.ignored?(view_name)
            view = View.new(name: view_name, definition: env.connection.view_definition(view_name))
            env.dump.tables[view.name] = view
            env.dump.depends(view.name, view.definition.scan(re_view_referent).flatten)
          end
        end

**Comment by ronen** [comment]
@RichardGrossman I can't reproduce this behavior in my tests.  Maybe there's some interaction with something else in your environment.  Are you using other gems that stick their fingers into AR's behavior?

Also, the problem might not technically be in schema_plus_views (which just adds views to the dump) but rather in schema_plus_core (which sticks its fingers into AR's dumping mechanism).  Could you try adding schema_plus_core but *not* schema_plus_views to your app, and see what happens?  Ideally it should be a no-op.  But if the USERS table disappears with just schema_plus_core, that'll tell us something.

**Comment by RichardGrossman** [comment]
Can you reproduce it using my tests?

**Comment by ronen** [comment]
@RichardGrossman I made a completely new app and went through the series of steps you listed, and didn't get the buggy behavior -- both 'users' and 'usersx' get dumped into db/schema.rb

**Comment by RichardGrossman** [comment]
You are absolutely right - and the situation is even weirder.

In my app, I removed the userx view, I renamed the users table to xusers, and it still doesn't show up when the schema-plus-views gem is installed!

Here's the SQL for the table:

- Table: xusers

-- DROP TABLE xusers;
```
CREATE TABLE xusers
(
  id integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
  client_id integer,
  username character varying,
  firstname character varying,
  lastname character varying,
  email character varying,
  primary_phone character varying,
  secondary_phone character varying,
  mobile_phone_texts character varying,
  occupation character varying,
  employer character varying,
  property_id integer,
  about text,
  is_staff boolean,
  payment_methods character varying,
  created_at timestamp without time zone NOT NULL,
  updated_at timestamp without time zone NOT NULL,
  is_receiving_texts boolean,
  is_mobile_phone_validated boolean,
  is_admin boolean,
  encrypted_password character varying NOT NULL DEFAULT ''::character varying,
  reset_password_token character varying,
  reset_password_sent_at timestamp without time zone,
  remember_created_at timestamp without time zone,
  sign_in_count integer NOT NULL DEFAULT 0,
  current_sign_in_at timestamp without time zone,
  last_sign_in_at timestamp without time zone,
  current_sign_in_ip inet,
  last_sign_in_ip inet,
  confirmation_token character varying,
  confirmed_at timestamp without time zone,
  confirmation_sent_at timestamp without time zone,
  unconfirmed_email character varying,
  failed_attempts integer NOT NULL DEFAULT 0,
  unlock_token character varying,
  locked_at timestamp without time zone,
  CONSTRAINT users_pkey PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE xusers
  OWNER TO cyberbeach;

-- Index: index_users_on_confirmation_token

-- DROP INDEX index_users_on_confirmation_token;

CREATE UNIQUE INDEX index_users_on_confirmation_token
  ON xusers
  USING btree
  (confirmation_token COLLATE pg_catalog."default");

-- Index: index_users_on_email

-- DROP INDEX index_users_on_email;

CREATE UNIQUE INDEX index_users_on_email
  ON xusers
  USING btree
  (email COLLATE pg_catalog."default");

-- Index: index_users_on_reset_password_token

-- DROP INDEX index_users_on_reset_password_token;

CREATE UNIQUE INDEX index_users_on_reset_password_token
  ON xusers
  USING btree
  (reset_password_token COLLATE pg_catalog."default");

-- Index: index_users_on_unlock_token

-- DROP INDEX index_users_on_unlock_token;

CREATE UNIQUE INDEX index_users_on_unlock_token
  ON xusers
  USING btree
  (unlock_token COLLATE pg_catalog."default");

**Comment by ronen** [comment]
Very strange!  Would you be willing to do a bit of debugging?

Maybe add 

```ruby
require 'byebug' ; byebug
```

before this line: https://github.com/SchemaPlus/schema_plus_core/blob/master/lib/schema_plus/core/active_record/schema_dumper.rb#L43  Then step into `super` and see if you can follow along as it gets the list of tables from the pg gem and loops through them, and maybe you'll be able to see where it goes astray?

**Comment by RichardGrossman** [comment]
I debugged a different way:  this looked suspicious to me in the xusers table schema on Postgres:

```encrypted_password character varying NOT NULL DEFAULT ''::character varying,```

so I changed to this:

```encrypted_password character varying NOT NULL,```

and that cured the problem.

However, this column is created by the installation of Devise, so I would think that anyone using Devise might run into this.  

Anyone else using Devise in an app along with the schema_plus_views gem, can you look and see if your users table has the encrypted_password column in Postgress defined in the first format with the  
```DEFAULT ''::character varying``` ???

**Comment by RichardGrossman** [comment]
Can't reproduce in current version - thanks for looking into this - closing.
